//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FnsParticipants/SearchFnsParticipantsResponse.proto
namespace Diadoc.Api.Proto.FnsParticipants
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFnsParticipantsResponse")]
  public partial class SearchFnsParticipantsResponse : global::ProtoBuf.IExtensible
  {
    public SearchFnsParticipantsResponse() {}
    
    private Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus _Status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private readonly global::System.Collections.Generic.List<Diadoc.Api.Proto.FnsParticipants.FnsParticipant> _Participants = new global::System.Collections.Generic.List<Diadoc.Api.Proto.FnsParticipants.FnsParticipant>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Participants", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Diadoc.Api.Proto.FnsParticipants.FnsParticipant> Participants
    {
      get { return _Participants; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FnsParticipant")]
  public partial class FnsParticipant : global::ProtoBuf.IExtensible
  {
    public FnsParticipant() {}
    
    private string _FnsParticipantId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FnsParticipantId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FnsParticipantId
    {
      get { return _FnsParticipantId; }
      set { _FnsParticipantId = value; }
    }
    private string _Inn;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Inn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Inn
    {
      get { return _Inn; }
      set { _Inn = value; }
    }

    private string _Kpp = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Kpp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Kpp
    {
      get { return _Kpp; }
      set { _Kpp = value; }
    }
    private string _FullName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"FullName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FullName
    {
      get { return _FullName; }
      set { _FullName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FnsParticipantSearchStatus")]
    public enum FnsParticipantSearchStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnknownFnsParticipantSearchStatus", Value=0)]
      UnknownFnsParticipantSearchStatus = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OkFnsParticipantSearchStatus", Value=1)]
      OkFnsParticipantSearchStatus = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotFoundFnsParticipantSearchStatus", Value=2)]
      NotFoundFnsParticipantSearchStatus = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotAllowedFnsParticipantSearchStatus", Value=3)]
      NotAllowedFnsParticipantSearchStatus = 3
    }
  
}