//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FnsParticipants/SearchFnsParticipantsRequest.proto
namespace Diadoc.Api.Proto.FnsParticipants
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SearchFnsParticipantsRequest")]
  public partial class SearchFnsParticipantsRequest : global::ProtoBuf.IExtensible
  {
    public SearchFnsParticipantsRequest() {}
    

    private string _Inn = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Inn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Inn
    {
      get { return _Inn; }
      set { _Inn = value; }
    }

    private string _Kpp = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Kpp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Kpp
    {
      get { return _Kpp; }
      set { _Kpp = value; }
    }

    private string _FnsParticipantId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"FnsParticipantId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FnsParticipantId
    {
      get { return _FnsParticipantId; }
      set { _FnsParticipantId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}