//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetOrCreateRoamingOrganizationByFnsParticipantIdRequest.proto
namespace Diadoc.Api.Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOrCreateRoamingOrganizationByFnsParticipantIdRequest")]
  public partial class GetOrCreateRoamingOrganizationByFnsParticipantIdRequest : global::ProtoBuf.IExtensible
  {
    public GetOrCreateRoamingOrganizationByFnsParticipantIdRequest() {}
    
    private string _FnsParticipantId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FnsParticipantId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FnsParticipantId
    {
      get { return _FnsParticipantId; }
      set { _FnsParticipantId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}